version: 2
updates:
- package-ecosystem: "pub"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "abhishekbhaskar"
- package-ecosystem: "pub"
  directory: "/1"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "sachin-sandhu"
- package-ecosystem: "pub"
  directory: "/2"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "randhircs"
- package-ecosystem: "pub"
  directory: "/3"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "markhallen"
- package-ecosystem: "pub"
  directory: "/4"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "kbukum1"
- package-ecosystem: "pub"
  directory: "/5"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "robaiken"
- package-ecosystem: "pub"
  directory: "/5"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "thavaahariharangit"
