version: 2
updates:
- package-ecosystem: "pub"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/1"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/2"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/3"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/4"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/5"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
- package-ecosystem: "pub"
  directory: "/6"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
