version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,9"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
