version: 2
updates:
- package-ecosystem: "npm"
  directory: "/6"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "abhishekbhaskar1"
- package-ecosystem: "pub"
  directories:
    - "/1/frontend/"
    - "/2/backend/"
    - "/1/libs-*"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "sachin-sandhu"
    - "kbukum1"
- package-ecosystem: "elm"
  directory: "/2"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "randhircs"
- package-ecosystem: "dotnet-sdk"
  directory: "/7"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "markhallen"
- package-ecosystem: "pub"
  directory: "/4"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "kbukum1"
- package-ecosystem: "pub"
  directory: "/5"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "robaiken"
    - "sachin-sandhu"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 8 * * 2,7"
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
  reviewers: 
    - "thavaahariharangit"
